`ASAP-Alchemy`: BespokeFit integration
asapdiscovery/asapdiscovery pull request #1115
Opened 2024-06-25 11:27 UTC by jthorton

## Description
This PR extends the `ASAP-Alchemy` CLI to interface with `openff-bespokefit`. This exposes three new commands 
- `asap-alchemy bespoke submit`: Submit the ligands in a local network to a bespokefit server
- `asap-alchemy bespoke status`: Get the status breakdown for ligands in a local network
- `asap-alchemy bespoke gather`: Get the bespoke parameters derived for the ligands in the local network

We have also updated the `asap-alchemy submit` command to automatically inject the bespoke parameters required for a given transformation into the force field when creating the OpenFE inputs. Note that only the parameters needed for the edge are included which should trigger the deduplication of the task in alchemiscale as more bespoke parameters are derived for a chemical series. 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [ ] tests
- [ ] update cli docs
- [ ] update tutorial docs 

## Questions
- [ ] Question 1 ..

## Status
- [ ] Ready to go

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-06-26 09:08 UTC, jthorton commented
Testing is blocked, till we get a new bespokefit release and an alchemiscale release which works with gufe and openfe >=1.

2024-10-13 22:59 UTC, hmacdope commented
With @jthorton we are pursuing a different path where we just pretrain a forcefield and host as an artifact. 

Due to the way bespokefit does its server-worker communication, there is a need to open  database http ports on the open internet which is not a good idea. 

We will leave this open as an example of how this might be done for the future.

2024-10-14 15:44 UTC, jthorton commented
@hmacdope & @JenkeScheen  can I get a quick look over this? We need this to submit the calculations for the bespokefit benchmarking we can run it from the branch though if we don't want this in main.

2024-10-15 03:09 UTC, hmacdope requested changes
Looking fantastic, my only request is that you write a Notion or docs document showing how this can be used in practice including with the bespokefit server on HPC. :) Can either go on ASAP notion or in the docs.

2024-10-15 03:09 UTC, hmacdope commented on asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py
> -class AlchemiscaleSettings(BaseSettings):
Good idea to move.

2024-10-15 03:09 UTC, hmacdope commented on asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py
> +        return ff_string
Very nice.

2024-10-15 03:09 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/schema/ligand.py
> +    bespoke_parameters: Optional[BespokeParameters] = Field(
Nice.

2024-10-16 14:55 UTC, jthorton commented
Thanks @hmacdope added some simple CLI docs on how to use the interface let me know what you think!

2024-10-16 15:02 UTC, jthorton commented
@hmacdope just noticed the docs are not building on the PR any more not sure what has happened

2024-10-17 10:13 UTC, hmacdope approved these changes

2024-10-17 12:43 UTC, merged