Ml model ensembles
asapdiscovery/asapdiscovery pull request #1145
Opened 2024-07-22 03:38 UTC by hmacdope

## Description
Adds ability to pull an ML model ensemble from a remote specification at a URL. 

## Developers certificate of origin
- [X] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-07-22 03:38 UTC, hmacdope commented
@kaminow  I would love to hear your thoughts here.

2024-07-22 15:05 UTC, kaminow requested changes
a couple nitpicky things but overall looks really good!

2024-07-23 01:03 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +                            else "2024-02-06"
Ah good catch, debugging.

2024-07-23 01:04 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +    def check_all_last_updated(cls, models):
No I suppose not, will remove.

2024-07-23 01:05 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +                models[model] = RemoteEnsembleHelper.to_ensemble_spec()
yes good catch

2024-07-23 02:21 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +    mtenn_lower_pin: "0.5.0"
I think lets just leave it as specified for the ensemble.

2024-07-23 05:34 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +            )
Done

2024-07-23 05:34 UTC, hmacdope commented
@kaminow probably ready for another look.

2024-07-25 14:07 UTC, kaminow approved these changes
two minor suggestions/questions but other than that looks good!

2024-07-25 14:07 UTC, kaminow commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +    return True
this works so fine to leave it is as, but could also do something like gather all lower pins and upper pins, then just make sure the `mtenn` version is between the highest lower pin and lowest upper pin (I think this is equivalent)

2024-07-25 14:07 UTC, kaminow commented on asapdiscovery-ml/asapdiscovery/ml/models.py
> +                    "remote_ensemble" in model_data and model_data["remote_ensemble"]
is this documented anywhere? sorry if I'm just being dumb and missing it

2024-07-26 01:38 UTC, merged