Small additions to asap-genetics seq-alignment
asapdiscovery/asapdiscovery pull request #1182
Opened 2024-08-29 23:13 UTC by mariacm12

## Description
Adding a few small additions to `asap-genetics seq-alignment`

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Small fixes to previous version .
- [x] Improved keyword selection of sequences, taking a string of comma-separated keywords (allows custom selection).
- [x] `--color-seq-match` option for the html viz highlights exact and same-group aminoacid matches.
- [ ] Testing? 

## Questions
- [ ] Question 1 ..

## Status
- [ ] Ready to go

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-09-10 17:44 UTC, mariacm12 commented
@hmacdope I made some tests for the sequence alignment and they seem to run successfully. I had a merge conflict with the `test_files.yaml` file because a recent PR modified it too. I solved it, but now pre-commit.ci is giving an error because the new file in the yaml is not being used (it is, just not on the current files in this branch). Do you know how to fix this?

2024-09-10 22:42 UTC, hmacdope commented
> @hmacdope I made some tests for the sequence alignment and they seem to run successfully. I had a merge conflict with the `test_files.yaml` file because a recent PR modified it too. I solved it, but now pre-commit.ci is giving an error because the new file in the yaml is not being used (it is, just not on the current files in this branch). Do you know how to fix this?

This looks like its a problem on main too, I will fix and then you can merge here.

2024-09-13 00:30 UTC, hmacdope requested changes
Looks great, some small changes. We need to get the MacOS runner working again as well.

2024-09-13 00:30 UTC, hmacdope commented on asapdiscovery-genetics/asapdiscovery/genetics/blast.py
> +        Number of alignments, alignments parameter in BLAST, by default 500
Default in function is 50, either change docs or default

2024-09-13 00:30 UTC, hmacdope commented on asapdiscovery-genetics/asapdiscovery/genetics/seq_alignment.py
> +class AAcid:
This is nice, but simpler would probably to use `BioPython.seq1` or `BioPython.seq3` instead of MDAnalysis.

2024-09-13 00:30 UTC, hmacdope commented on asapdiscovery-genetics/asapdiscovery/genetics/seq_alignment.py
> +        agroups = {
As this is only needed once per interpreter you can make it a constant outside of class scope

```python 

_AMINO_ACID_GROUPS = {...}

class AminoAcid:

    
    def __init__(...):
    
   def get_aminoacid_group(self):
       for key in _AMINO_ACID_GROUPS:
           ...
```

2024-09-13 00:30 UTC, hmacdope commented on asapdiscovery-genetics/asapdiscovery/genetics/seq_alignment.py
> +        aa_colors = {
Same with this, make `_AMINO_ACID_COLOURS` and then you can use it anywhere.

2024-09-16 19:32 UTC, mariacm12 reviewed
I added the changes you suggested. I'm not sure why the MacOS test isn't working though. Is it a problem with the tests or with the runner? @hmacdope

2024-09-16 21:39 UTC, hmacdope commented
> I added the changes you suggested. I'm not sure why the MacOS test isn't working though. Is it a problem with the tests or with the runner? @hmacdope

Do the tests pass locally on your Mac? They seem to be fine on linux on my box. It could be the runner, I will re-trigger and see what happens, otherwise we can just add a skip with:
```python
@pytest.mark.skipif(
    os.getenv("RUNNER_OS") == "macOS", reason="Test failing on GHA runner, fine locally, see issue #blah"
)
```

2024-09-17 00:23 UTC, hmacdope commented
> > I added the changes you suggested. I'm not sure why the MacOS test isn't working though. Is it a problem with the tests or with the runner? @hmacdope
> 
> Do the tests pass locally on your Mac? They seem to be fine on linux on my box. It could be the runner, I will re-trigger and see what happens, otherwise we can just add a skip with:
> 
> ```python
> @pytest.mark.skipif(
>     os.getenv("RUNNER_OS") == "macOS", reason="Test failing on GHA runner, fine locally, see issue #blah"
> )
> ```

@mariacm12 seems like its persistent. If it works on your Mac, then I would say add a skip.

2024-09-18 23:58 UTC, hmacdope commented
OK running in serial didn't help.

2024-09-18 23:59 UTC, hmacdope approved these changes

2024-09-19 02:34 UTC, merged