Add filter on fluorescence experimental errors
asapdiscovery/asapdiscovery pull request #1243
Opened 2024-10-11 18:56 UTC by kaminow

Add filter on fluorescence experimental errors to prevent overly large errors from rounding the readout values to 0/10. Closes #1234.

2024-10-11 19:10 UTC, kaminow commented
@hmacdope I think this is ready, lmk if you think there's anything else we want to do. rather than removing stuff here I just set the IC50 and pIC50 values to NaNs since they should be removed later in the pipeline anyway, but we can change if you think we should just remove the offending rows

2024-10-15 00:37 UTC, hmacdope requested changes
Great work! I say we leave in the backup clipping L488-498, what do you think?

2024-10-15 00:37 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/util/utils.py
> +                # @HMO do we want to leave the stderr values as they are for posterity
Log them as a warning I think would be good.

2024-10-15 00:37 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/util/utils.py
> +                #  or set them to NaN as well?
Set them to `nan` I think is the right move.

2024-10-15 00:37 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/cli_mlops.py
> +    "--pic50-stderr-filt",
Nice, thanks.

2024-10-15 08:25 UTC, hmacdope commented
Also @kaminow you will need to merge with `upstream/main`

2024-10-15 13:57 UTC, kaminow commented
@hmacdope I think ready for another review!

also, which file are you referring to here?
> Great work! I say we leave in the backup clipping L488-498, what do you think?

2024-10-17 01:39 UTC, hmacdope commented
> @hmacdope I think ready for another review!
> 
> also, which file are you referring to here?
> 
> > Great work! I say we leave in the backup clipping L488-498, what do you think?

asapdiscovery-ml/asapdiscovery/ml/cli_mlops.py , but should be all good.

2024-10-17 01:39 UTC, hmacdope approved these changes

2024-10-17 02:39 UTC, merged