add progress bar to `alchemy` docking (`prep run`)
asapdiscovery/asapdiscovery pull request #1255
Opened 2024-10-18 09:05 UTC by JenkeScheen

fixes https://github.com/asapdiscovery/asapdiscovery/issues/1202

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-10-18 16:15 UTC, JenkeScheen commented
I'm going to also add a progress bar to the charging stage, and work in some exception catches that I run into for some large sets that we're running

2024-10-21 01:00 UTC, hmacdope requested changes
Just a few drive by comments, looking good otherwise.

2024-10-21 01:00 UTC, hmacdope commented on asapdiscovery-docking/asapdiscovery/docking/schema/pose_generation.py
> +                except RuntimeError:
Add progress bar in same way to non-parallel calculation.

2024-10-22 03:03 UTC, JenkeScheen commented
@hmacdope I'm going to tackle ligand outlier catching in another PR, let's keep this PR simple by only adding progress bars.

2024-10-22 05:43 UTC, hmacdope commented on asapdiscovery-docking/asapdiscovery/docking/schema/pose_generation.py
> +                progressbar.update(1)
Not defined on this branch.

2024-10-22 09:53 UTC, hmacdope approved these changes
LGTM

2024-10-22 10:55 UTC, merged